version: "3.4"

volumes:
  portainer_data: {}

networks:
  proxy:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16


services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    networks:
      - proxy
    volumes:
      - ${PROJECT_ROOT}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      # Accept self-signed backend certificates
      - "--serversTransport.insecureSkipVerify=true"
      # Only accept access to traefik dashboard through proxy.
      - "--api.insecure=false"
      # enables the use of labels on services
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      # http/https entrypoints
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # ssl certificate
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${DOMAIN_CONTACT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      # global redirect http to https middleware
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # traefik dashboard
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`proxy.${DOMAIN}`)" # The dashboard will be available at proxy.yourdomain.tld change this as you which
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    expose:
      - 9000
    networks:
      - proxy
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)" # Again the container will be available at "portainer.yourdomain.tld"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      - ${PROJECT_ROOT}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev:/dev
    privileged: true
    # To make ha able to use "auto discover" set network mode to "host"
    # I've had issued connecting to IKEA Gateway and Chromecasts when running in
    # container network. I would like ha to run on a docker defined network, but has not
    # been able to get it to work good so far.
    network_mode: host
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hahttp.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.ha.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.ha.tls=true"
      - "traefik.http.routers.ha.tls.certresolver=myresolver"
      - "traefik.http.routers.ha.tls.domains[0].main=home.${DOMAIN}"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ${PROJECT_ROOT}/mosquitto:/mosquitto
    networks:
      - default
    ports:
      - "1883:1883"
      - "9001:9001"

  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    network_mode: host # For same reason as ha
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ${PROJECT_ROOT}/nodered/data:/data
    depends_on:
      - homeassistant