version: "3.4"

volumes:
  portainer_data: {}

networks:
  proxy:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16


services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    networks:
      - proxy
    volumes:
      - ${PROJECT_ROOT}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    command:
      # Accept self-signed backend certificates
      - "--serversTransport.insecureSkipVerify=true"
      # Only accept access to traefik dashboard through proxy.
      - "--api.insecure=true"
      # enables the use of labels on services
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      # http/https entrypoints
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: homeassistant
    volumes:
      - ${PROJECT_ROOT}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev:/dev
    privileged: true
    # To make ha able to use "auto discover" set network mode to "host"
    # I've had issued connecting to IKEA Gateway and Chromecasts when running in
    # container network. I would like ha to run on a docker defined network, but has not
    # been able to get it to work good so far.
    network_mode: host
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ${PROJECT_ROOT}/mosquitto:/mosquitto
    networks:
      - default
    ports:
      - "1883:1883"
      - "9001:9001"

  nodered:
    container_name: nodered
    image: nodered/node-red
    restart: unless-stopped
    network_mode: host # For same reason as ha
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ${PROJECT_ROOT}/nodered/data:/data
    depends_on:
      - homeassistant